//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolest
    {
        public Bolest()
        {
            this.dijagnozas = new HashSet<Dijagnoza>();
        }
    
        public int ID_bolest { get; set; }
        public string Naziv { get; set; }
    
        public virtual ICollection<Dijagnoza> dijagnozas { get; set; }
    }
}
