//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class cjepivo
    {
        public cjepivo()
        {
            this.kontrolas = new HashSet<kontrola>();
        }
    
        public int ID_cjepiva { get; set; }
        public string ime_cjepiva { get; set; }
        public double doza_cjepiva { get; set; }
        public string proizvodac_cjepiva { get; set; }
        public System.DateTime rok_trajanja { get; set; }
        public double cijena { get; set; }
    
        public virtual ICollection<kontrola> kontrolas { get; set; }
    }
}
