//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MazaEntities : DbContext
    {
        public MazaEntities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bolest> Bolest { get; set; }
        public DbSet<Cjepivo> Cjepivo { get; set; }
        public DbSet<Dijagnoza> Dijagnoza { get; set; }
        public DbSet<Kontrola> Kontrola { get; set; }
        public DbSet<Lijek> Lijek { get; set; }
        public DbSet<Operacija> Operacija { get; set; }
        public DbSet<PropisaniLijek> PropisaniLijek { get; set; }
        public DbSet<Veterinar> Veterinar { get; set; }
        public DbSet<Vlasnik> Vlasnik { get; set; }
        public DbSet<Zivotinja> Zivotinja{ get; set; }
        public DbSet<ViewPrikazZivotinja> ViewPrikazZivotinja { get; set; }
        public DbSet<viewKontrola> viewKontrola { get; set; }
    }
}
