//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bolest> bolests { get; set; }
        public DbSet<Cjepivo> cjepivoes { get; set; }
        public DbSet<Dijagnoza> dijagnozas { get; set; }
        public DbSet<Kontrola> kontrolas { get; set; }
        public DbSet<Lijek> Lijeks { get; set; }
        public DbSet<Operacija> operacijas { get; set; }
        public DbSet<PropisaniLijek> propisani_lijek { get; set; }
        public DbSet<Veterinar> veterinars { get; set; }
        public DbSet<Vlasnik> vlasniks { get; set; }
        public DbSet<Zivotinja> zivotinjas { get; set; }
    }
}
