//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bolest> bolests { get; set; }
        public DbSet<cjepivo> cjepivoes { get; set; }
        public DbSet<dijagnoza> dijagnozas { get; set; }
        public DbSet<kontrola> kontrolas { get; set; }
        public DbSet<Lijek> Lijeks { get; set; }
        public DbSet<operacija> operacijas { get; set; }
        public DbSet<propisani_lijek> propisani_lijek { get; set; }
        public DbSet<veterinar> veterinars { get; set; }
        public DbSet<vlasnik> vlasniks { get; set; }
        public DbSet<Zivotinja> zivotinjas { get; set; }
    }
}
