//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola
    {
        public Kontrola()
        {
            this.Dijagnoza = new HashSet<Dijagnoza>();
            this.Operacija = new HashSet<Operacija>();
            this.Cjepivo = new HashSet<Cjepivo>();
        }
    
        public int IdKontrola { get; set; }
        public int IdZivotinja { get; set; }
        public int IdVeterinar { get; set; }
        public System.DateTime DatumKontrole { get; set; }
        public string Status { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<Dijagnoza> Dijagnoza { get; set; }
        public virtual ICollection<Operacija> Operacija { get; set; }
        public virtual Veterinar Veterinar { get; set; }
        public virtual Zivotinja Zivotinja { get; set; }
        public virtual ICollection<Cjepivo> Cjepivo { get; set; }
    }
}
