//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class kontrola
    {
        public kontrola()
        {
            this.dijagnozas = new HashSet<dijagnoza>();
            this.operacijas = new HashSet<operacija>();
            this.cjepivoes = new HashSet<cjepivo>();
        }
    
        public int ID_kontrola { get; set; }
        public int ID_zivotinja { get; set; }
        public int ID_veterinar { get; set; }
        public System.DateTime datum_kontrole { get; set; }
        public string status { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<dijagnoza> dijagnozas { get; set; }
        public virtual ICollection<operacija> operacijas { get; set; }
        public virtual veterinar veterinar { get; set; }
        public virtual zivotinja zivotinja { get; set; }
        public virtual ICollection<cjepivo> cjepivoes { get; set; }
    }
}
