//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrola
    {
        public Kontrola()
        {
            this.dijagnozas = new HashSet<Dijagnoza>();
            this.operacijas = new HashSet<Operacija>();
            this.cjepivoes = new HashSet<Cjepivo>();
        }
    
        public int ID_kontrola { get; set; }
        public int ID_zivotinja { get; set; }
        public int ID_veterinar { get; set; }
        public System.DateTime datum_kontrole { get; set; }
        public string status { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<Dijagnoza> dijagnozas { get; set; }
        public virtual ICollection<Operacija> operacijas { get; set; }
        public virtual Veterinar veterinar { get; set; }
        public virtual Zivotinja zivotinja { get; set; }
        public virtual ICollection<Cjepivo> cjepivoes { get; set; }
    }
}
