//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijek
    {
        public Lijek()
        {
            this.PropisaniLijek = new HashSet<PropisaniLijek>();
        }
    
        public int IdLijek { get; set; }
        public string Naziv { get; set; }
        public string Proizvodac { get; set; }
        public double Cijena { get; set; }
        public string Uputstva { get; set; }
        public Nullable<System.DateTime> RokTrajanja { get; set; }
    
        public virtual ICollection<PropisaniLijek> PropisaniLijek { get; set; }
    }
}
