//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijek
    {
        public Lijek()
        {
            this.propisani_lijek = new HashSet<propisani_lijek>();
        }
    
        public int ID_lijek { get; set; }
        public string naziv { get; set; }
        public string proizvodac { get; set; }
        public double cijena { get; set; }
        public string uputstva { get; set; }
        public Nullable<System.DateTime> rok_trajanja { get; set; }
    
        public virtual ICollection<propisani_lijek> propisani_lijek { get; set; }
    }
}
