//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacija
    {
        public int IdOperacija { get; set; }
        public string VrstaZahvata { get; set; }
        public Nullable<System.TimeSpan> TrajanjeZahtjeva { get; set; }
        public string Napomena { get; set; }
        public System.DateTime DatumZahvata { get; set; }
        public int IdKontrola { get; set; }
    
        public virtual Kontrola Kontrola { get; set; }
    }
}
