//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacija
    {
        public int ID_operacija { get; set; }
        public string vrsta_zahvata { get; set; }
        public Nullable<System.TimeSpan> trajanje_zahvata { get; set; }
        public string napomena { get; set; }
        public System.DateTime datum_zahvata { get; set; }
        public int kontrola_ID_kontrola { get; set; }
    
        public virtual Kontrola kontrola { get; set; }
    }
}
