//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropisaniLijek
    {
        public int IdLijek { get; set; }
        public int IdDijagnoza { get; set; }
        public string Napomena { get; set; }
    
        public virtual Dijagnoza Dijagnoza { get; set; }
        public virtual Lijek Lijek { get; set; }
    }
}
