//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class propisani_lijek
    {
        public int ID_lijek { get; set; }
        public int ID_dijagnoza { get; set; }
        public string napomena { get; set; }
    
        public virtual dijagnoza dijagnoza { get; set; }
        public virtual Lijek Lijek { get; set; }
    }
}
