//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinar
    {
        public Veterinar()
        {
            this.Kontrola = new HashSet<Kontrola>();
        }
    
        public int IdVeterinar { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string AdresaStanovanja { get; set; }
        public string BrojTelefona1 { get; set; }
        public string BrojTelefona2 { get; set; }
        public string Titula { get; set; }
        public System.DateTime DatumZaposlenja { get; set; }
        public System.DateTime DatumRodenja { get; set; }
        public string korime { get; set; }
        public string lozinka { get; set; }
    
        public virtual ICollection<Kontrola> Kontrola { get; set; }
    }
}
