//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPrikazZivotinja
    {
        public int ZivotinjaID { get; set; }
        public string Ime { get; set; }
        public string Spol { get; set; }
        public string Vrsta { get; set; }
        public System.DateTime Datum_Rođenja { get; set; }
        public Nullable<int> Broj_Čipa { get; set; }
        public int Težina { get; set; }
        public Nullable<System.DateTime> Datum_Uginuća { get; set; }
        public string Ime_Vlasnika { get; set; }
        public string Prezime_Vlasnika { get; set; }
    }
}
