//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewKontrola
    {
        public int ID_kontrola { get; set; }
        public string zivotinja { get; set; }
        public string veterinar { get; set; }
        public string opis { get; set; }
        public string status { get; set; }
        public System.DateTime datum_kontrole { get; set; }
    }
}
