//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlasnik
    {
        public Vlasnik()
        {
            this.Zivotinja = new HashSet<Zivotinja>();
        }
    
        public int ID_vlasnik { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string adresa_stavnovanja { get; set; }
        public string broj_telefona1 { get; set; }
        public string broj_telefona2 { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Zivotinja> Zivotinja { get; set; }
    }
}
