//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_t18024_Maza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zivotinja
    {
        public Zivotinja()
        {
            this.Kontrola = new HashSet<Kontrola>();
        }
    
        public int IdZivotinja { get; set; }
        public string Ime { get; set; }
        public string Spol { get; set; }
        public string Vrsta { get; set; }
        public System.DateTime DatumRodenja { get; set; }
        public Nullable<int> BrojCipa { get; set; }
        public int Tezina { get; set; }
        public Nullable<System.DateTime> DatumUginuca { get; set; }
        public int IdVlasnika { get; set; }
    
        public virtual ICollection<Kontrola> Kontrola { get; set; }
        public virtual Vlasnik Vlasnik { get; set; }
    }
}
